name: Unit tests
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/paramark/mmm-base-lightweight:noavx-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Python unit tests
        run: pytest test/

